// ─── BILINGUAL CONTENT ───────────────────────────────────────────────────────
// All translations for the Mozart Requiem presentation.
// Each movement/theme has parallel fa (Persian) and en (English) fields.
// Each Latin text snippet also carries a `phon` field with Ecclesiastical Latin
// pronunciation for choir/piano sight-reading. CAPITALS mark stressed syllables.

export const movements = [
  {
    num: "I", latin: "Introitus", arc: 55, color: "#4a6fa5",
    key: { fa: "ر مینور · آداجیو", en: "D minor · Adagio" },
    mood: { fa: "باشکوه", en: "Majestic" },
    author: { fa: "موتزارت — کامل", en: "Mozart — complete" },
    sheetUrl: null,
    fa: {
      title: "درآمد", sub: "ورود به مراسم — نخستین دعا",
      meaning: "موتزارت مراسم را نه با وحشت، بلکه با دعا آغاز می‌کند — دو خواسته که کل اثر را شکل می‌دهند: آرامش و نور.\n\nآخرین جمله عمیق‌ترین حقیقت این مراسم را بیان می‌کند: «تمام آدمیان نزد تو خواهند آمد.» هیچ استثنایی وجود ندارد. سفری که در پیش است سفر همگان است.",
      note: "این تنها موومانی است که موتزارت پیش از مرگش به‌طور کامل ارکسترال کرد. هر نتی که می‌شنوید از اوست.",
    },
    en: {
      title: "Introit", sub: "The Entrance to the Mass — the First Prayer",
      meaning: "Mozart begins the Mass not with terror, but with prayer — the two desires that shape the entire work: peace and light.\n\nThe final line speaks the deepest truth of this Mass: \"all humanity shall come to you.\" There is no exception. The journey ahead is everyone's journey.",
      note: "This is the only movement Mozart fully orchestrated before his death. Every note you hear is his.",
    },
    text: [
      { la: "Requiem aeternam dona eis, Domine,\net lux perpetua luceat eis.",
        phon: "REH-kwee-em eh-TEHR-nahm DOH-nah EH-ees, DOH-mee-neh,\net looks pehr-PEH-too-ah LOO-cheh-aht EH-ees.",
        fa: "پروردگارا، آرامش ابدی به آنان ببخش،\nو نور جاودان بر آنان بتابد.",
        en: "Eternal rest grant unto them, O Lord,\nand let perpetual light shine upon them." },
      { la: "Exaudi orationem meam,\nad te omnis caro veniet.",
        phon: "ek-SOW-dee oh-rah-tsee-OH-nem MEH-ahm,\nahd teh OHM-nees KAH-roh VEH-nee-et.",
        fa: "دعایم را بشنو،\nکه تمام آدمیان نزد تو خواهند آمد.",
        en: "Hear my prayer,\nto thee all flesh shall come." },
    ],
  },
  {
    num: "II", latin: "Kyrie", arc: 60, color: "#4a6fa5",
    key: { fa: "ر مینور · آلگرو · فوگ مضاعف", en: "D minor · Allegro · Double Fugue" },
    mood: { fa: "انضباطی", en: "Disciplined" },
    author: { fa: "موتزارت — کامل", en: "Mozart — complete" },
    sheetUrl: null,
    fa: {
      title: "کیری", sub: "دعا برای رحمت — تنها متن یونانی",
      meaning: "کیری کهن‌ترین متن در کل مراسم است — آنقدر کهن که هرگز از یونانی ترجمه نشد. کلمه «الئیسون» فریاد ناتوان در برابر قدرتمند مطلق است.\n\nموتزارت این چند هجا را به‌صورت فوگ مضاعف می‌نویسد: دو موضوع موسیقی که در هم تنیده‌اند. شکل خود الهیات را بیان می‌کند — رحمت با مسیح گره خورده؛ نمی‌توان آن‌ها را از هم جدا کرد.",
      note: "موتزارت موضوع فوگ را از هندل وام گرفت. در پایان به همین موسیقی باز می‌گردد — اما آنگاه دعا پاسخ یافته است.",
    },
    en: {
      title: "Kyrie", sub: "A Prayer for Mercy — the Only Greek Text",
      meaning: "The Kyrie is the most ancient text in the entire Mass — so ancient it was never translated from Greek. The word eleison is the cry of the powerless before the all-powerful.\n\nMozart sets these few syllables as a double fugue: two musical subjects woven together. The form itself states the theology — mercy is bound to Christ; they cannot be separated.",
      note: "Mozart borrowed the fugue subject from Handel. He returns to this same music at the end — but by then the prayer has been answered.",
    },
    text: [
      { la: "Kyrie eleison.\nChriste eleison.\nKyrie eleison.",
        phon: "KEE-ree-eh eh-LEH-ee-sohn.\nKREE-steh eh-LEH-ee-sohn.\nKEE-ree-eh eh-LEH-ee-sohn.",
        fa: "پروردگارا، رحم کن.\nمسیحا، رحم کن.\nپروردگارا، رحم کن.",
        en: "Lord, have mercy.\nChrist, have mercy.\nLord, have mercy." },
    ],
  },
  {
    num: "III", latin: "Dies Irae", arc: 5, color: "#8b1e1e",
    key: { fa: "ر مینور · آلگرو آسای", en: "D minor · Allegro assai" },
    mood: { fa: "آخرالزمانی", en: "Apocalyptic" },
    author: { fa: "موتزارت (طرح‌کلی)", en: "Mozart (sketch)" },
    sheetUrl: null,
    fa: {
      title: "روز خشم", sub: "آغاز سکانس قرون وسطایی",
      meaning: "پس از دو موومان دعای آرام، پرده دریده می‌شود. این شعر لاتین قرن سیزدهم پایان جهان را توصیف می‌کند.\n\nجفت‌شدن عجیب «داوود» پیامبر عبری و «سیبیل» کاهنه رومی را در نظر بگیرید. هر دو سنت همان پایان را پیش‌گویی کرده‌اند. هیچ فرهنگی مصون نیست.\n\nواژه فاویلا به معنای «اخگر» است — نه خاکستر سرد، بلکه بازمانده آتش. جهان تنها پایان نمی‌یابد؛ می‌سوزد.",
      note: null,
    },
    en: {
      title: "Dies Irae", sub: "The Medieval Sequence Begins",
      meaning: "After two movements of quiet prayer, the curtain is torn. This 13th-century Latin poem describes the end of the world.\n\nConsider the strange pairing of \"David,\" the Hebrew prophet, with \"Sibyl,\" the Roman oracle. Both traditions foretold the same end. No culture is exempt.\n\nThe word favilla means \"ember\" — not cold ash, but the remnant of fire. The world does not merely end; it burns.",
      note: null,
    },
    text: [
      { la: "Dies irae, dies illa,\nsolvet saeclum in favilla,\nteste David cum Sibylla.",
        phon: "DEE-ehs EE-reh, DEE-ehs EEL-lah,\nSOHL-vet SEH-kloom een fah-VEEL-lah,\nTEH-steh DAH-veed koom see-BEEL-lah.",
        fa: "روز خشم، آن روز،\nجهان را به خاکستر تبدیل خواهد کرد،\nچنان‌که داوود و سیبیل پیشگویی کردند.",
        en: "Day of wrath, that day,\nshall dissolve the world into embers,\nas David and the Sibyl foretold." },
      { la: "Quantus tremor est futurus,\nquando judex est venturus.",
        phon: "KWAHN-toos TREH-mor est foo-TOO-roos,\nKWAHN-doh YOO-dex est ven-TOO-roos.",
        fa: "چه لرزش عظیمی خواهد بود\nآنگاه که داوری فرا می‌رسد.",
        en: "What dread shall be\nwhen the Judge shall come." },
    ],
  },
  {
    num: "IV", latin: "Tuba Mirum", arc: 18, color: "#8b1e1e",
    key: { fa: "سی♭ ماژور · آندانته", en: "B♭ major · Andante" },
    mood: { fa: "شگفت‌زده", en: "Awestruck" },
    author: { fa: "موتزارت (طرح‌کلی)", en: "Mozart (sketch)" },
    sheetUrl: null,
    fa: {
      title: "شیپور شگفت‌انگیز", sub: "رستاخیز مردگان",
      meaning: "تصویر شیپوری که مردگان را از گور فرامی‌خواند از قدیس پولس (اول قرنتیان ۱۵:۵۲) است. موتزارت آن را واقعی می‌کند — تنبون تنور سولو این موومان را آغاز می‌کند، تنها، یکی از مشهورترین سولوهای تنبون در موسیقی کلاسیک.\n\nسپس کتاب می‌آید — دفتری که در آن هر عمل هر زندگی ثبت شده. چهار سولیست یکی‌یکی وارد می‌شوند — باس، تنور، آلتو، سوپرانو — هر کدام در پیشگاه تخت می‌ایستند.",
      note: null,
    },
    en: {
      title: "Tuba Mirum", sub: "The Resurrection of the Dead",
      meaning: "The image of a trumpet calling the dead from their graves comes from St. Paul (1 Corinthians 15:52). Mozart makes it real — a solo trombone, alone, opens this movement, one of the most famous trombone solos in classical music.\n\nThen the Book is opened — a ledger in which every act of every life is recorded. The four soloists enter one by one — bass, tenor, alto, soprano — each stepping before the throne.",
      note: null,
    },
    text: [
      { la: "Tuba mirum spargens sonum\nper sepulcra regionum,\ncoget omnes ante thronum.",
        phon: "TOO-bah MEE-room SPAR-jens SOH-noom\npehr seh-POOL-krah reh-jee-OH-noom,\nKOH-jet OHM-nehs AHN-teh TROH-noom.",
        fa: "شیپور با نوای شگفت‌انگیزش\nبر فراز گورستان‌های سرزمین‌ها طنین می‌اندازد،\nهمگان را پیش تخت فرامی‌خواند.",
        en: "The trumpet, scattering its wondrous sound\nthrough the tombs of every land,\nshall summon all before the throne." },
      { la: "Liber scriptus proferetur,\nunde mundus judicetur.",
        phon: "LEE-behr SKREEP-toos proh-feh-REH-toor,\nOON-deh MOON-doos yoo-dee-CHEH-toor.",
        fa: "کتاب نوشته‌شده بیرون آورده می‌شود،\nکه جهان بر اساس آن داوری خواهد شد.",
        en: "The written book shall be brought forth,\nfrom which the world shall be judged." },
    ],
  },
  {
    num: "V", latin: "Rex Tremendae", arc: 30, color: "#8b1e1e",
    key: { fa: "سل مینور · گراو", en: "G minor · Grave" },
    mood: { fa: "التماس", en: "Pleading" },
    author: { fa: "موتزارت (طرح‌کلی)", en: "Mozart (sketch)" },
    sheetUrl: null,
    fa: {
      title: "شاه هیبت‌انگیز", sub: "شاه عظمت بی‌پایان",
      meaning: "مفصل الهیاتی کل سکانس داوری. متن دو ایده را در تنش غیرقابل‌تحمل نگه می‌دارد: خدا پادشاهی هراس‌انگیز و مطلق است — و با این حال رایگان (گراتیس) نجات می‌دهد. این واژه ریشه کلمه انگلیسی «گریس» است.\n\nدو هجای پایانی: سالوا مه. مرا نجات ده. تا این لحظه خدا به‌صورت سوم شخص توصیف شده بود. ناگهان دعا شخصی می‌شود. روح از میان جمعیت بیرون آمده.",
      note: "موتزارت این را با آکوردهای پرقدرت می‌نویسد، سپس برای دو هجای التماس‌گونه به زمزمه فرو می‌نشیند.",
    },
    en: {
      title: "Rex Tremendae", sub: "King of Boundless Majesty",
      meaning: "The theological hinge of the entire Judgment sequence. The text holds two ideas in unbearable tension: God is a fearsome and absolute king — and yet saves freely (gratis). This word is the root of the English \"grace.\"\n\nThe last two syllables: salva me. Save me. Until this moment, God has been described in the third person. Suddenly the prayer becomes personal. The soul has stepped out from the crowd.",
      note: "Mozart writes this with thundering chords, then sinks to a whisper for the two pleading syllables.",
    },
    text: [
      { la: "Rex tremendae majestatis,\nqui salvandos salvas gratis,\nsalva me, fons pietatis.",
        phon: "REKS treh-MEN-deh mah-yeh-STAH-tees,\nkwee sahl-VAHN-dohs SAHL-vahs GRAH-tees,\nSAHL-vah meh, fohns pee-eh-TAH-tees.",
        fa: "ای شاه عظمت هیبت‌انگیز،\nکه نجات‌یافتگان را رایگان نجات می‌دهی،\nمرا نجات ده، ای سرچشمه مهربانی.",
        en: "King of dreadful majesty,\nwho freely savest those to be saved,\nsave me, O fount of mercy." },
    ],
  },
  {
    num: "VI", latin: "Recordare", arc: 40, color: "#7a4f1e",
    key: { fa: "فا ماژور · آندانته", en: "F major · Andante" },
    mood: { fa: "صمیمی", en: "Intimate" },
    author: { fa: "موتزارت (طرح‌کلی)", en: "Mozart (sketch)" },
    sheetUrl: null,
    fa: {
      title: "به یاد آر", sub: "جسورانه‌ترین استدلال روح",
      meaning: "روح جسورانه‌ترین حرکت الهیاتی در کل مراسم را انجام می‌دهد: به مسیح یادآوری می‌کند که چرا آمده. «من دلیل سفر توام.» اگر مسیح گنه‌کار را نجات ندهد، تمام رنج‌های مسیح بیهوده بوده.\n\nموتزارت طولانی‌ترین موومان سکانس را اینجا می‌نویسد — بیش از شش دقیقه، فقط چهار سولیست، بدون کر. مذاکره‌ای آرام میان روح و مسیح، در گوشه‌ای از دادگاه.",
      note: null,
    },
    en: {
      title: "Recordare", sub: "The Soul's Boldest Argument",
      meaning: "The soul makes the boldest theological move in the entire Mass: it reminds Christ why he came. \"I am the cause of your journey.\" If Christ does not save the sinner, all of Christ's suffering was in vain.\n\nMozart writes the longest movement of the sequence here — over six minutes, just four soloists, no chorus. A quiet negotiation between soul and Christ, in a corner of the courtroom.",
      note: null,
    },
    text: [
      { la: "Recordare, Jesu pie,\nquod sum causa tuae viae,\nne me perdas illa die.",
        phon: "reh-kohr-DAH-reh, YEH-soo PEE-eh,\nkwohd soom KOW-sah TOO-eh VEE-eh,\nneh meh PEHR-dahs EEL-lah DEE-eh.",
        fa: "به یاد آر، عیسای مهربان،\nکه من دلیل سفر توام،\nمرا در آن روز از دست مده.",
        en: "Remember, merciful Jesus,\nthat I am the cause of thy journey,\nlest thou cast me away on that day." },
      { la: "Tantus labor non sit cassus.",
        phon: "TAHN-toos LAH-bor nohn seet KAHS-soos.",
        fa: "این همه زحمت بیهوده نباشد.",
        en: "Let not such labor be in vain." },
    ],
  },
  {
    num: "VII", latin: "Confutatis", arc: 8, color: "#8b1e1e",
    key: { fa: "لا مینور ← فا ماژور", en: "A minor → F major" },
    mood: { fa: "دوگانه", en: "Dual" },
    author: { fa: "موتزارت (عمدتاً)", en: "Mozart (mostly)" },
    sheetUrl: null,
    fa: {
      title: "جدایی روح‌ها", sub: "هنگامی که ملعونان محکوم می‌شوند",
      meaning: "لحظه جدایی. تصویرسازی روانشناختی موتزارت یکی از بزرگ‌ترین‌هاست: صداهای مردانه خط «ملعونان» را با غرش‌های خشمگین پایین می‌خوانند — مجازات قابل شنیدن. در برابر آن‌ها، صداهای زنانه در فرازی آرام شناور هستند — بهشت، دست‌نخورده از هرج‌ومرج پایین.\n\nهر دو جهان را در یک اندازه می‌شنوید. جهنم در پایین صفحه. بهشت در بالا. روح فریاد می‌زند: وکا مه — «مرا [با آنان] بخوان».",
      note: null,
    },
    en: {
      title: "Confutatis", sub: "When the Damned Are Condemned",
      meaning: "The moment of separation. Mozart's psychological imagery is among his greatest: male voices sing the \"damned\" line with furious roars below — punishment made audible. Against them, female voices float in a calm ascent above — heaven, untouched by the chaos below.\n\nYou hear both worlds at the same scale. Hell at the bottom of the page. Heaven at the top. The soul cries out: voca me — \"call me [with them].\"",
      note: null,
    },
    text: [
      { la: "Confutatis maledictis,\nflammis acribus addictis,\nvoca me cum benedictis.",
        phon: "kohn-foo-TAH-tees mah-leh-DEEK-tees,\nFLAHM-mees AH-kree-boos ahd-DEEK-tees,\nVOH-kah meh koom beh-neh-DEEK-tees.",
        fa: "هنگامی که ملعونان محکوم می‌شوند\nو به شعله‌های تند محکوم می‌گردند،\nمرا با برکت‌یافتگان بخوان.",
        en: "When the damned are confounded\nand consigned to the bitter flames,\ncall thou me with the blessed." },
      { la: "Cor contritum quasi cinis,\ngere curam mei finis.",
        phon: "kohr kohn-TREE-toom KWAH-zee CHEE-nees,\nJEH-reh KOO-rahm MEH-ee FEE-nees.",
        fa: "قلبم مثل خاکستر خرد شده،\nپایان مرا سرپرستی کن.",
        en: "My heart contrite as ashes,\ncare thou for my final end." },
    ],
  },
  {
    num: "VIII", latin: "Lacrimosa", arc: 52, color: "#3d5a80",
    key: { fa: "ر مینور · لارگتو", en: "D minor · Larghetto" },
    mood: { fa: "گریان", en: "Tearful" },
    author: { fa: "۸ میزان موتزارت، بقیه زوسمایر", en: "8 bars Mozart, rest by Süssmayr" },
    sheetUrl: null,
    fa: {
      title: "سرشار از اشک", sub: "اینجاست که موتزارت قلم را زمین گذاشت",
      meaning: "سکانس نه با وحشت، بلکه با اشک پایان می‌یابد. پس از توصیف خشم، شیپور، تخت، جدایی — متن بالاخره اجازه می‌دهد که گریه کند.\n\nدستور زبان دعا تغییر می‌کند: «آرامش به آنان ببخش.» عزادار دیگر برای خود التماس نمی‌کند؛ برای همه مردگان دعا می‌کند.\n\nهشت میزان بعد، روی کلمات «یودیکاندوس هومو ریوس» — گنه‌کاری که باید داوری شود — موتزارت دیگر ننوشت. آن شب مُرد.",
      note: "پنجم دسامبر ۱۷۹۱. اینها آخرین میزان‌هایی هستند که موتزارت نوشت. روی کلمات «گنه‌کاری که باید داوری شود» متوقف شد.",
    },
    en: {
      title: "Lacrimosa", sub: "Where Mozart Set Down His Pen",
      meaning: "The sequence ends not with terror but with tears. After the descriptions of wrath, trumpet, throne, separation — the text finally allows itself to weep.\n\nThe grammar of the prayer changes: \"grant them rest.\" The mourner no longer pleads for self; he prays for all the dead.\n\nEight measures in, on the words judicandus homo reus — the sinner who must be judged — Mozart wrote no more. That night, he died.",
      note: "December 5, 1791. These are the last bars Mozart wrote. He stopped on the words \"the sinner who must be judged.\"",
    },
    text: [
      { la: "Lacrimosa dies illa,\nqua resurget ex favilla\njudicandus homo reus.",
        phon: "lah-kree-MOH-zah DEE-ehs EEL-lah,\nkwah reh-SOOR-jet eks fah-VEEL-lah\nyoo-dee-KAHN-doos OH-moh REH-oos.",
        fa: "آن روز سرشار از اشک خواهد بود،\nآنگاه که گنه‌کار\nاز خاکستر برخیزد تا داوری شود.",
        en: "That tearful day,\nwhen from the embers shall arise\nthe guilty man to be judged." },
      { la: "Huic ergo parce, Deus,\ndona eis requiem. Amen.",
        phon: "OO-eek EHR-goh PAHR-cheh, DEH-oos,\nDOH-nah EH-ees REH-kwee-em. AH-men.",
        fa: "پس بر او رحم کن، ای خدا،\nآرامش به آنان ببخش. آمین.",
        en: "Then spare him, O God,\ngrant them rest. Amen." },
    ],
  },
  {
    num: "IX", latin: "Domine Jesu", arc: 62, color: "#4a6fa5",
    key: { fa: "سل مینور · آندانته", en: "G minor · Andante" },
    mood: { fa: "دسترسی", en: "Reaching" },
    author: { fa: "موتزارت (طرح‌کلی)", en: "Mozart (sketch)" },
    sheetUrl: null,
    fa: {
      title: "خداوندا عیسی", sub: "آغاز پیشکش — دعا برای رهایی",
      meaning: "داوری تمام شد. حالا پیشکشی آغاز می‌شود — جایی که مراسم به‌طور رسمی دعاها را به نمایندگی از مردگان تقدیم می‌کند.\n\nدستور زبان کاملاً به «آنان را رها کن» تغییر کرده. عزادار دیگر تنها نیست. این موومان با فوگی روی کلمات «کوام اولیم آبراهاه پرومیسیستی» پایان می‌یابد — استناد به کهن‌ترین پیمان در تورات.",
      note: null,
    },
    en: {
      title: "Domine Jesu", sub: "The Offering Begins — Prayer for Deliverance",
      meaning: "The judgment is over. Now the offering begins — where the Mass formally presents prayers on behalf of the dead.\n\nThe grammar has shifted entirely to \"deliver them.\" The mourner is no longer alone. This movement ends with a fugue on the words quam olim Abrahae promisisti — a citation of the most ancient covenant in the Torah.",
      note: null,
    },
    text: [
      { la: "Domine Jesu Christe, Rex gloriae,\nlibera animas omnium fidelium defunctorum\nde poenis inferni et de profundo lacu.",
        phon: "DOH-mee-neh YEH-soo KREE-steh, REKS GLOH-ree-eh,\nLEE-beh-rah AH-nee-mahs OHM-nee-oom fee-DEH-lee-oom deh-foonk-TOH-room\ndeh PEH-nees een-FEHR-nee et deh proh-FOON-doh LAH-koo.",
        fa: "خداوندا عیسی مسیح، شاه جلال،\nارواح تمام مؤمنان درگذشته را\nاز عذاب دوزخ و چاه عمیق رها کن.",
        en: "Lord Jesus Christ, King of Glory,\ndeliver the souls of all the faithful departed\nfrom the pains of hell and the deep pit." },
      { la: "Libera eas de ore leonis.",
        phon: "LEE-beh-rah EH-ahs deh OH-reh leh-OH-nees.",
        fa: "آنان را از دهان شیر برهان.",
        en: "Deliver them from the mouth of the lion." },
    ],
  },
  {
    num: "X", latin: "Hostias", arc: 72, color: "#5a7d5a",
    key: { fa: "می♭ ماژور · آندانته", en: "E♭ major · Andante" },
    mood: { fa: "اعتماد", en: "Trusting" },
    author: { fa: "موتزارت (طرح‌کلی)", en: "Mozart (sketch)" },
    sheetUrl: null,
    fa: {
      title: "قربانی‌ها و دعاها", sub: "پیشکش و امید",
      meaning: "واژه هوستیا به معنای «قربانی» در لاتین است — همان ریشه‌ای که به انگلیسی کلمه Host، نان مقدس مراسم عشای ربانی را می‌دهد.\n\nعبارت پایانی بیانیه الهیاتی صریح این اثر است: د مورته ترانسیره آد ویتام. «از مرگ به زندگی عبور ده.» مرگ مقصد نیست؛ گذرگاه است. روح باید از آن بگذرد.",
      note: null,
    },
    en: {
      title: "Hostias", sub: "Sacrifices and Prayers",
      meaning: "The word hostia means \"sacrifice\" in Latin — the same root that gives English the word Host, the consecrated bread of the Eucharist.\n\nThe closing phrase is the explicit theological statement of the work: de morte transire ad vitam. \"Pass from death to life.\" Death is not a destination; it is a passage. The soul must cross through it.",
      note: null,
    },
    text: [
      { la: "Hostias et preces tibi, Domine,\nlaudis offerimus.",
        phon: "OH-stee-ahs et PREH-chehs TEE-bee, DOH-mee-neh,\nLOW-dees ohf-FEH-ree-moos.",
        fa: "قربانی‌ها و دعاهای ستایش\nبه تو تقدیم می‌کنیم، پروردگارا.",
        en: "We offer to thee, O Lord,\nsacrifices and prayers of praise." },
      { la: "Fac eas, Domine,\nde morte transire ad vitam.",
        phon: "fahk EH-ahs, DOH-mee-neh,\ndeh MOHR-teh trahn-SEE-reh ahd VEE-tahm.",
        fa: "آنان را، خداوندا،\nاز مرگ به زندگی عبور ده.",
        en: "Grant them, O Lord,\nto pass from death to life." },
    ],
  },
  {
    num: "XI", latin: "Sanctus", arc: 68, color: "#5a7d5a",
    key: { fa: "ر ماژور · آداجیو", en: "D major · Adagio" },
    mood: { fa: "فرشته‌وار", en: "Angelic" },
    author: { fa: "عمدتاً زوسمایر", en: "Mostly Süssmayr" },
    sheetUrl: null,
    fa: {
      title: "قدوس", sub: "سرود فرشتگان",
      meaning: "تنها لحظه‌ای در مراسم که انسان‌ها آنچه فرشتگان می‌خوانند را می‌خوانند. از اشعیا ۶:۳، جایی که پیامبر سرافیمان را دور تخت خدا می‌بیند.\n\nتغییر گام را بشنوید. سرود روان تقریباً تمام وقت در ر مینور بوده. سنکتوس به ر ماژور می‌رود — همان نت پایه، اما ناگهان آسمان گشوده شده.",
      note: null,
    },
    en: {
      title: "Sanctus", sub: "The Angels' Hymn",
      meaning: "The only moment in the Mass where humans sing what the angels sing. From Isaiah 6:3, where the prophet sees the seraphim around the throne of God.\n\nListen for the key change. The Requiem has been almost entirely in D minor. The Sanctus moves to D major — the same fundamental note, but suddenly heaven has opened.",
      note: null,
    },
    text: [
      { la: "Sanctus, sanctus, sanctus,\nDominus Deus Sabaoth.",
        phon: "SAHNK-toos, SAHNK-toos, SAHNK-toos,\nDOH-mee-noos DEH-oos SAH-bah-oht.",
        fa: "قدوس، قدوس، قدوس،\nخداوند خدای لشکرها.",
        en: "Holy, holy, holy,\nLord God of Hosts." },
      { la: "Pleni sunt caeli et terra gloria tua.\nHosanna in excelsis.",
        phon: "PLEH-nee soont CHEH-lee et TEHR-rah GLOH-ree-ah TOO-ah.\noh-ZAHN-nah een ek-SHEHL-sees.",
        fa: "آسمان و زمین از جلال تو پر است.\nهوسانا در اعلا.",
        en: "Heaven and earth are full of thy glory.\nHosanna in the highest." },
    ],
  },
  {
    num: "XII", latin: "Benedictus", arc: 72, color: "#5a7d5a",
    key: { fa: "سی♭ ماژور · آندانته", en: "B♭ major · Andante" },
    mood: { fa: "استقبال", en: "Welcoming" },
    author: { fa: "موتزارت/زوسمایر", en: "Mozart / Süssmayr" },
    sheetUrl: null,
    fa: {
      title: "مبارک باد آنکه می‌آید", sub: "متبرک است آنکه به نام خداوند می‌آید",
      meaning: "فریاد جمعیت هنگام ورود مسیح به اورشلیم در یکشنبه شاخه‌ها. مراسم این مسیح که به اورشلیم آمد را با مسیحی که به محراب می‌آید یکی می‌داند.\n\nبرای چهار سولیست نوشته شده — صمیمی، لطیف، مثل چهار صدایی که به آینده‌ای خوش‌آمد می‌گویند.",
      note: null,
    },
    en: {
      title: "Benedictus", sub: "Blessed Is He Who Comes in the Name of the Lord",
      meaning: "The cry of the crowd as Christ entered Jerusalem on Palm Sunday. The Mass identifies the Christ who came to Jerusalem with the Christ who comes to the altar.\n\nWritten for the four soloists — intimate, tender, like four voices welcoming a coming future.",
      note: null,
    },
    text: [
      { la: "Benedictus qui venit\nin nomine Domini.\nHosanna in excelsis.",
        phon: "beh-neh-DEEK-toos kwee VEH-neet\neen NOH-mee-neh DOH-mee-nee.\noh-ZAHN-nah een ek-SHEHL-sees.",
        fa: "متبرک است آنکه\nبه نام خداوند می‌آید.\nهوسانا در اعلا.",
        en: "Blessed is he that cometh\nin the name of the Lord.\nHosanna in the highest." },
    ],
  },
  {
    num: "XIII", latin: "Agnus Dei", arc: 78, color: "#5a7d5a",
    key: { fa: "ر مینور · لارگتو", en: "D minor · Larghetto" },
    mood: { fa: "پذیرش", en: "Accepting" },
    author: { fa: "عمدتاً زوسمایر", en: "Mostly Süssmayr" },
    sheetUrl: null,
    fa: {
      title: "بره خدا", sub: "که گناه جهان را می‌برد",
      meaning: "از یحیای تعمیددهنده: «اینک بره خدا که گناه جهان را می‌برد.» مسیح را با بره فصح عهد عبری یکی می‌کند.\n\nکلمه واحد سمپیترنام — جاودان — چیزی است که کل اثر به سوی آن حرکت کرده. ترس تمام شده. آنچه می‌ماند درخواستی است که این آرامش، وقتی آمد، هرگز پایان نیابد.",
      note: null,
    },
    en: {
      title: "Agnus Dei", sub: "Who Takes Away the Sin of the World",
      meaning: "From John the Baptist: \"Behold the Lamb of God who takes away the sin of the world.\" It identifies Christ with the Passover lamb of the Hebrew Covenant.\n\nThe single word sempiternam — everlasting — is what the entire work has been moving toward. The fear is over. What remains is the request that this peace, when it comes, should never end.",
      note: null,
    },
    text: [
      { la: "Agnus Dei, qui tollis peccata mundi,\ndona eis requiem.",
        phon: "AH-nyoos DEH-ee, kwee TOHL-lees pek-KAH-tah MOON-dee,\nDOH-nah EH-ees REH-kwee-em.",
        fa: "ای بره خدا، که گناه جهان را می‌بری،\nآرامش به آنان ببخش.",
        en: "Lamb of God, who takest away the sins of the world,\ngrant them rest." },
      { la: "Agnus Dei, qui tollis peccata mundi,\ndona eis requiem sempiternam.",
        phon: "AH-nyoos DEH-ee, kwee TOHL-lees pek-KAH-tah MOON-dee,\nDOH-nah EH-ees REH-kwee-em sem-pee-TEHR-nahm.",
        fa: "ای بره خدا، که گناه جهان را می‌بری،\nآرامش جاودان به آنان ببخش.",
        en: "Lamb of God, who takest away the sins of the world,\ngrant them everlasting rest." },
    ],
  },
  {
    num: "XIV", latin: "Lux Aeterna", arc: 88, color: "#c8982a",
    key: { fa: "ر مینور ← ر ماژور", en: "D minor → D major" },
    mood: { fa: "درخشان", en: "Radiant" },
    author: { fa: "بازاستفاده از درآمد", en: "Reusing the Introit" },
    sheetUrl: null,
    fa: {
      title: "نور ابدی", sub: "نور جاودان — بازگشت به آغاز",
      meaning: "دو خواسته اولین موومان — آرامش و نور — بالاخره با هم فرا می‌رسند. سفر از خلال وحشت، داوری، جدایی و غم به مقصدش رسیده: نوری که هرگز پایان نمی‌یابد.\n\nمتن لاتین اینجا حرفاً سطرهایی از درآمد را تکرار می‌کند. موتزارت و زوسمایر این تقارن ساختاری را در موسیقی آشکار می‌کنند: موسیقی لوکس اترنا همان موسیقی درآمد است. سرود روان جایی که آغاز کرده پایان می‌یابد. اما روح حرکت کرده.",
      note: "دایره بسته می‌شود. روح گذر کرده.",
    },
    en: {
      title: "Lux Aeterna", sub: "Eternal Light — A Return to the Beginning",
      meaning: "The two desires of the first movement — peace and light — finally arrive together. The journey through terror, judgment, separation and grief has reached its destination: a light that never ends.\n\nThe Latin text here literally repeats lines from the Introit. Mozart and Süssmayr reveal this structural symmetry in the music: the music of Lux Aeterna is the music of the Introit. The Requiem ends where it began. But the soul has moved.",
      note: "The circle is closed. The soul has passed through.",
    },
    text: [
      { la: "Lux aeterna luceat eis, Domine,\ncum sanctis tuis in aeternum,\nquia pius es.",
        phon: "looks eh-TEHR-nah LOO-cheh-aht EH-ees, DOH-mee-neh,\nkoom SAHNK-tees TOO-ees een eh-TEHR-noom,\nKWEE-ah PEE-oos es.",
        fa: "نور ابدی بر آنان بتابد، پروردگارا،\nبا قدیسانت تا ابد،\nزیرا که تو مهربانی.",
        en: "Let eternal light shine upon them, O Lord,\nwith thy saints forever,\nfor thou art merciful." },
      { la: "Requiem aeternam dona eis, Domine,\net lux perpetua luceat eis.",
        phon: "REH-kwee-em eh-TEHR-nahm DOH-nah EH-ees, DOH-mee-neh,\net looks pehr-PEH-too-ah LOO-cheh-aht EH-ees.",
        fa: "آرامش ابدی به آنان ببخش، پروردگارا،\nو نور جاودان بر آنان بتابد.",
        en: "Eternal rest grant unto them, O Lord,\nand let perpetual light shine upon them." },
    ],
  },
  {
    num: "XV", latin: "Cum Sanctis Tuis", arc: 95, color: "#c8982a",
    key: { fa: "ر مینور ← ر ماژور · فوگ", en: "D minor → D major · Fugue" },
    mood: { fa: "ابدی", en: "Eternal" },
    author: { fa: "بازاستفاده از فوگ کیری", en: "Reusing the Kyrie fugue" },
    sheetUrl: null,
    fa: {
      title: "با قدیسان تو", sub: "با قدیسانت تا ابد — فوگ پایانی",
      meaning: "آخرین کلمات یک درخواست نیستند. بیان اعتماد هستند. کویا پیوس اس — «زیرا که تو مهربانی.» روح دیگر نمی‌خواهد. در پاسخ آرام گرفته.\n\nموتزارت فوگ کیری را دوباره به کار می‌گیرد — همان نت‌هایی که برای رحمت التماس می‌کردند حالا با اطمینان می‌خوانند. روحی که فریاد «پروردگارا، رحم کن» سر داده بود حالا «با قدیسانت تا ابد، زیرا که تو مهربانی» می‌خواند.\n\nآخرین آکورد در ر ماژور است — یک سوم پیکاردی. سایه در نور حل می‌شود.",
      note: "اثر در گامی پایان می‌یابد که تمام وقت از آن پرهیز کرده بود: ر ماژور. نور.",
    },
    en: {
      title: "Cum Sanctis Tuis", sub: "With Thy Saints Forever — The Final Fugue",
      meaning: "The last words are not a request. They are an expression of trust. quia pius es — \"for thou art merciful.\" The soul no longer asks. It has rested in the answer.\n\nMozart reuses the Kyrie fugue — the same notes that begged for mercy now sing in confidence. The soul that cried \"Lord, have mercy\" now sings \"with thy saints forever, for thou art merciful.\"\n\nThe final chord is in D major — a Picardy third. The shadow resolves into light.",
      note: "The work ends in a key it had avoided the entire time: D major. Light.",
    },
    text: [
      { la: "Cum sanctis tuis in aeternum,\nquia pius es.",
        phon: "koom SAHNK-tees TOO-ees een eh-TEHR-noom,\nKWEE-ah PEE-oos es.",
        fa: "با قدیسانت تا ابد،\nزیرا که تو مهربانی.",
        en: "With thy saints forever,\nfor thou art merciful." },
    ],
  },
];

export const themes = [
  { icon: "☩", latin: "requiem · sempiternam",
    fa: { name: "آرامش", desc: "نخستین کلمه مراسم و مرکزی‌ترین خواسته آن. به‌صورت سرود روان آغاز می‌شود و با سرود روان سمپیترنام — آرامش ابدی — پایان می‌یابد. سفر فاصله میان این دو عبارت است." },
    en: { name: "Peace", desc: "The first word of the Mass and its most central desire. Begins as requiem and ends with requiem sempiternam — eternal peace. The journey is the distance between these two phrases." } },
  { icon: "✦", latin: "lux · luceat · aeterna",
    fa: { name: "نور", desc: "با آرامش در درآمد جفت می‌شود، سپس در طول داوری تقریباً غایب است، و در پایان غالب می‌شود. روح از دعا برای نور به ایستادن در آن حرکت می‌کند." },
    en: { name: "Light", desc: "Paired with peace in the Introit, almost absent during the Judgment, then becomes dominant at the end. The soul moves from praying for light to standing within it." } },
  { icon: "♡", latin: "eleison · pius es",
    fa: { name: "رحمت", desc: "در کیری التماس می‌شود. در رکس ترمندا به‌عنوان طبیعت خدا نامیده می‌شود. در کلمات پایانی به‌عنوان واقعیت تأیید می‌شود: کویا پیوس اس — زیرا که تو مهربانی." },
    en: { name: "Mercy", desc: "Pleaded for in the Kyrie. Named as God's nature in Rex Tremendae. Affirmed as reality in the final words: quia pius es — for thou art merciful." } },
  { icon: "▲", latin: "favilla · flammis · cinis",
    fa: { name: "آتش و خاکستر", desc: "جهان در خاکستر ذوب می‌شود. ملعونان به شعله‌های تند محکوم می‌شوند. قلب «مثل خاکستر خرد شده». آتش واسطه هم داوری و هم ندامت است." },
    en: { name: "Fire and Ash", desc: "The world dissolves into ash. The damned are condemned to acrid flames. The heart is \"crushed like ash.\" Fire mediates both judgment and contrition." } },
  { icon: "⚖", latin: "Rex tremendae · Agnus Dei",
    fa: { name: "داور و بره", desc: "همان مسیح با دو نام خوانده می‌شود. در مرکز: داور هراس‌انگیز روی تخت. در پایان: بره‌ای که گناه را می‌برد. سرود روان به شنونده می‌آموزد که یکی را در دیگری ببیند." },
    en: { name: "Judge and Lamb", desc: "The same Christ called by two names. At the center: the fearsome judge on the throne. At the end: the lamb who takes away sin. The Requiem teaches the listener to see one in the other." } },
  { icon: "→", latin: "salva me → dona eis",
    fa: { name: "من ← آنان", desc: "دستور زبان دعا تغییر می‌کند. موومان‌های اولیه برای فرد التماس می‌کنند: مرا نجات ده. پس از لاکریموزا، روح برای همه مردگان دعا می‌کند: آرامش به آنان ببخش." },
    en: { name: "Me → Them", desc: "The grammar of the prayer changes. The early movements plead for the individual: save me. After Lacrimosa, the soul prays for all the dead: grant them rest." } },
  { icon: "↔", latin: "de morte transire ad vitam",
    fa: { name: "گذر", desc: "الهیات اثر در یک عبارت، پنهان در هوستیاس: مرگ پایان نیست بلکه گذرگاه است. کل سرود روان سفر آن عبور است." },
    en: { name: "Passage", desc: "The theology of the work in a single phrase, hidden in the Hostias: death is not an end but a crossing. The entire Requiem is the journey of that passage." } },
];

export const STR = {
  fa: {
    work: "سرود روان · کوشل ۶۲۶ · ۱۷۹۱",
    workFull: "سرود روان · کوشل ۶۲۶ · ولفگانگ آمادئوس موتزارت · ۱۷۹۱",
    composer: "ولفگانگ آمادئوس موتزارت",
    title1: "گذر روح",
    title2: "از سرود روان موتزارت",
    subtitleLatin: "REQUIEM · K. 626 · 1791",
    subtitleEn: "A MEDITATION IN FIFTEEN MOVEMENTS",
    blurb: "از نخستین دعا برای آرامش ابدی تا آخرین نور میان قدیسان — مراقبه‌ای بر مرگ، داوری و رحمت که در گور خود آهنگساز ناتمام ماند.",
    scrollHint: "↓ برای کاوش پایین بروید ↓",
    arcEyebrow: "قوس احساسی",
    arcTitlePre: "از ", arcDark: "تاریکی", arcTitlePost: " به نور",
    arcHint: "روی هر نقطه روی قوس یا هر کارت موومان کلیک کنید تا متن و معنا را ببینید.",
    arcHintMuseum: "روی هر نقطه روی قوس یا هر اتاق گالری کلیک کنید تا متن و معنا را بخوانید.",
    arcLabels: { peace: "آرامش", sorrow: "غم", dread: "وحشت" },
    moveEyebrow: "پانزده موومان — کلیک کنید تا باز شود",
    themesEyebrow: "نخ‌های تکرارشونده",
    themesEyebrowAlt: "نخ‌های در تار و پود اثر",
    themesEyebrowMuseum: "گالری دوم · مضامین",
    themesTitlePre: "هفت کلمه که ", themesTitleAccent: "کل معنا", themesTitlePost: " را حمل می‌کنند",
    movement: "موومان",
    latinHeader: "متن لاتین و ترجمه فارسی",
    phonHeader: "تلفظ کلیسایی لاتین",
    meaningHeader: "معنا و شرح",
    noteHeader: "یادداشت",
    fieldKey: "گام", fieldMood: "حال و هوا", fieldAuthor: "نویسنده", fieldTheme: "مضمون",
    galleryBar: "گالری موسیقی · نمایشگاه ویژه",
    galleryHall: "گالری اول · ورود رایگان",
    exhibitionLabel: "نمایشگاه ویژه",
    titleWallLine: "آخرین اثر ولفگانگ آمادئوس موتزارت، در پانزده موومان",
    titleWallMeta: "کوشل ۶۲۶ · ساخته شده ۱۷۹۱ · کامل شده ۱۷۹۲",
    titleWallText: [
      "در تابستان ۱۷۹۱، یک کمیسیون‌دهنده ناشناس یک مراسم سرود روان از ولفگانگ آمادئوس موتزارت سفارش داد. او زنده نمی‌ماند تا آن را تمام کند.",
      "این نمایشگاه موومان به موومان از اثر می‌گذرد — متن لاتین، معنای الهیاتی، و حرکات موسیقایی که موتزارت برای تجسم آن‌ها استفاده کرد.",
      "موتزارت در پنجم دسامبر ۱۷۹۱، در میان جمله، هشت میزان درون لاکریموزا درگذشت. شاگردش فرانتس کساویر زوسمایر نسخه نهایی را کامل کرد.",
    ],
    galleryFirst: "گالری اول · جهت‌گیری",
    arcEmotional: "احساسی",
    arcRoom: "قوس",
    figure: "شکل اول",
    clickDetails: "← برای جزئیات کامل کلیک کنید",
    exitWall: "دیوار خروج",
    closingTitle: "آهنگسازی که همراه روحی که می‌نوشت، می‌مُرد.",
    prologueEyebrow: "پیش‌درآمد",
    prologue: [
      "در تابستان ۱۷۹۱، پیکی ناشناس با سفارشی برای یک مراسم سرود روان به در خانه موتزارت آمد. کمیسیون‌دهنده — که بعدها کنت والزگ شناخته شد و قصد داشت اثر را به نام خود جا بزند — هرگز نمی‌دانست که عجیب‌ترین همکاری در تاریخ موسیقی را آغاز کرده.",
      "موتزارت سی و پنج ساله بود. تا پاییز بیمار شد. تا دسامبر موومان‌های ابتدایی را کامل کرده و بیشتر بقیه را طرح‌کلی زده بود و تنها هشت میزان از لاکریموزا نوشته بود، پیش از آنکه دیگر نتواند بنویسد.",
      "آنچه می‌شنوید مراقبه‌ای است درباره گذر روح از زندگی — که توسط مردی ساخته شده که در آن هفته‌های یکسان، دقیقاً همان گذر را می‌کرد.",
    ],
    concludingA: "موتزارت با این اثر ناتمام درگذشت — لاکریموزا در میان جمله قطع شد، روی کلمات",
    lacrimosaQuote: "«گنه‌کاری که باید داوری شود».",
    concludingB: "آنچه می‌شنوید مراقبه‌ای است درباره مرگ که توسط مردی ساخته شده که در همان هفته‌ها، دقیقاً آن گذر را می‌کرد. سرود روان فقط درباره گذر روح",
    notWord: "نیست",
    isWord: "هست",
    soulPassage: ". خودِ گذر روح ",
    finalPrayerFa1: "آرامش ابدی به آنان ببخش، پروردگارا،",
    finalPrayerFa2: "و نور جاودان بر آنان بتابد.",
    finalPrayerLa1: "Requiem aeternam dona eis, Domine,",
    finalPrayerLa2: "et lux perpetua luceat eis.",
    footer: "✦ ولفگانگ آمادئوس موتزارت · کوشل ۶۲۶ · ۱۷۹۱ ✦",
    footerLong: "ولفگانگ آمادئوس موتزارت · سرود روان در ر مینور · کوشل ۶۲۶ · ۱۷۹۱",
    sheetEyebrow: "نسخه نت‌ها · سایت‌ریدینگ",
    sheetTitle: "نت‌های اصلی برای کر و پیانو",
    sheetIntro: "برای هر موومان، نت اصلی کر و پیانو در دسترس است. روی هر موومان کلیک کنید تا نت را ببینید. تلفظ کلیسایی لاتین در زیر هر سطر آمده — حروف بزرگ هجای تأکیدی را نشان می‌دهد.",
    sheetPlaceholder: "نت در دسترس نیست — لطفاً فایل نت را در پوشه /public بارگذاری کنید",
    phonNote: "حروف بزرگ = هجای تأکیدی · تلفظ کلیسایی (ایتالیایی)",
    perfEyebrow: "نمای اجرا · فضای زنده",
    perfTitle: "صدا، تالار، سنگ",
    perfBlurb: "اثر در سه فضا زنده می‌شود — گروه کر، تالار ارکستر، و کلیسا. هر یک سهم خود را در رنگ صدا، طنین و معنا دارد.",
    perfMovementsEyebrow: "پانزده موومان — نمای صحنه",
    perfPlaceholder: "تصاویر هنوز افزوده نشده — فایل‌ها را در /public/perf/ بارگذاری کنید (choir.jpg · hall.jpg · church.jpg)",
    feedback: {
      openLabel: "ارسال نظر",
      eyebrow: "گفتگو با سازنده",
      title: "نظرت رو بگو",
      subtitle: "هر فکری درباره ساختار صفحه، ایده‌ای برای بهتر شدن، یا چیزی که اضافه/کم بشه — بنویس یا حرف بزن.",
      placeholder: "بنویس یا روی میکروفون کلیک کن تا صحبت کنی...",
      send: "ارسال",
      recording: "در حال شنیدن…",
      sending: "در حال ارسال…",
      sent: "ممنون! دریافت شد.",
      error: "ارسال نشد. دوباره تلاش کن.",
      contextHint: "این نظر مربوط به نمای:",
      micTitle: "صحبت برای متن",
      noSpeech: "مرورگر شما تشخیص گفتار را پشتیبانی نمی‌کند. لطفاً متن را تایپ کنید.",
      claudeReplyLabel: "پاسخ کلود",
    },
    viewLabels: {
      interactive: "تعاملی", poetic: "شعری", museum: "موزه‌ای",
      dramatic: "سینمایی", minimal: "ساده", editorial: "مجله‌ای",
      illuminated: "معنوی", performance: "اجرا", sheet: "نت‌ها",
    },
  },
  en: {
    work: "Requiem · K. 626 · 1791",
    workFull: "Requiem · K. 626 · Wolfgang Amadeus Mozart · 1791",
    composer: "Wolfgang Amadeus Mozart",
    title1: "The Soul's Passage",
    title2: "Through Mozart's Requiem",
    subtitleLatin: "REQUIEM · K. 626 · 1791",
    subtitleEn: "A MEDITATION IN FIFTEEN MOVEMENTS",
    blurb: "From the first prayer for eternal rest to the final light among the saints — a meditation on death, judgment and mercy that remained unfinished at the composer's own grave.",
    scrollHint: "↓ Scroll to explore ↓",
    arcEyebrow: "Emotional Arc",
    arcTitlePre: "From ", arcDark: "Darkness", arcTitlePost: " into Light",
    arcHint: "Click any point on the arc or any movement card to see the text and its meaning.",
    arcHintMuseum: "Click any point on the arc or any gallery room to read the text and its meaning.",
    arcLabels: { peace: "Peace", sorrow: "Sorrow", dread: "Dread" },
    moveEyebrow: "Fifteen Movements — click to open",
    themesEyebrow: "Recurring Threads",
    themesEyebrowAlt: "Threads Woven Through the Work",
    themesEyebrowMuseum: "Gallery II · Themes",
    themesTitlePre: "Seven Words That Carry ", themesTitleAccent: "the Whole Meaning", themesTitlePost: "",
    movement: "Movement",
    latinHeader: "Latin Text and English Translation",
    phonHeader: "Ecclesiastical Latin Pronunciation",
    meaningHeader: "Meaning and Commentary",
    noteHeader: "Note",
    fieldKey: "Key", fieldMood: "Mood", fieldAuthor: "Author", fieldTheme: "Theme",
    galleryBar: "Music Gallery · Special Exhibition",
    galleryHall: "Gallery I · Free Admission",
    exhibitionLabel: "Special Exhibition",
    titleWallLine: "The final work of Wolfgang Amadeus Mozart, in fifteen movements",
    titleWallMeta: "K. 626 · Composed 1791 · Completed 1792",
    titleWallText: [
      "In the summer of 1791, an anonymous patron commissioned a Requiem Mass from Wolfgang Amadeus Mozart. He would not live to finish it.",
      "This exhibition moves through the work movement by movement — the Latin text, its theological meaning, and the musical gestures Mozart used to embody them.",
      "Mozart died on December 5, 1791, mid-sentence, eight measures into the Lacrimosa. His pupil Franz Xaver Süssmayr completed the final version.",
    ],
    galleryFirst: "Gallery I · Orientation",
    arcEmotional: "Emotional",
    arcRoom: "Arc",
    figure: "Figure I",
    clickDetails: "Click for full details →",
    exitWall: "Exit Wall",
    closingTitle: "A composer dying alongside the soul he was writing.",
    prologueEyebrow: "Prologue",
    prologue: [
      "In the summer of 1791, an unknown messenger arrived at Mozart's door with a commission for a Requiem Mass. The patron — later identified as Count Walsegg, who intended to pass the work off as his own — could never have known he was setting in motion the strangest collaboration in the history of music.",
      "Mozart was thirty-five. By autumn he had fallen ill. By December he had finished the opening movements and sketched most of the rest, having written only eight bars of the Lacrimosa before he could write no more.",
      "What you hear is a meditation on the soul's passage out of life — composed by a man who, in those same weeks, was making exactly that passage.",
    ],
    concludingA: "Mozart died with this work unfinished — the Lacrimosa cut off mid-sentence, on the words",
    lacrimosaQuote: "\"the sinner who must be judged.\"",
    concludingB: "What you hear is a meditation on death composed by a man who, in those same weeks, was making exactly that passage. The Requiem is not merely",
    notWord: "about",
    isWord: "is",
    soulPassage: " the passage of the soul. It ",
    finalPrayerFa1: "Eternal rest grant unto them, O Lord,",
    finalPrayerFa2: "and let perpetual light shine upon them.",
    finalPrayerLa1: "Requiem aeternam dona eis, Domine,",
    finalPrayerLa2: "et lux perpetua luceat eis.",
    footer: "✦ Wolfgang Amadeus Mozart · K. 626 · 1791 ✦",
    footerLong: "Wolfgang Amadeus Mozart · Requiem in D minor · K. 626 · 1791",
    sheetEyebrow: "Score Edition · Sight Reading",
    sheetTitle: "Original Choral and Piano Score",
    sheetIntro: "For each movement, the original choir and piano score is available. Click any movement to view the sheet music. Ecclesiastical Latin pronunciation appears beneath each line — capital letters indicate the stressed syllable.",
    sheetPlaceholder: "Score not available — please upload the sheet music file to /public",
    phonNote: "CAPITALS = stressed syllable · Ecclesiastical (Italianate) pronunciation",
    perfEyebrow: "Performance View · Living Space",
    perfTitle: "Voice, Hall, Stone",
    perfBlurb: "The work comes alive in three spaces — the choir, the orchestra hall, and the church. Each contributes its colour of sound, its resonance, its meaning.",
    perfMovementsEyebrow: "Fifteen Movements — Scene View",
    perfPlaceholder: "Photos not yet added — upload files to /public/perf/ (choir.jpg · hall.jpg · church.jpg)",
    feedback: {
      openLabel: "Send feedback",
      eyebrow: "Talk to the maker",
      title: "Share your thoughts",
      subtitle: "Any idea about the page structure, suggestion, or anything to add or remove — type it or speak it.",
      placeholder: "Type, or click the microphone to speak...",
      send: "Send",
      recording: "Listening…",
      sending: "Sending…",
      sent: "Thank you — received.",
      error: "Could not send. Try again.",
      contextHint: "About the view:",
      micTitle: "Speak to text",
      noSpeech: "Your browser does not support speech recognition. Please type your message.",
      claudeReplyLabel: "Claude's reply",
    },
    viewLabels: {
      interactive: "Interactive", poetic: "Poetic", museum: "Museum",
      dramatic: "Cinematic", minimal: "Minimal", editorial: "Editorial",
      illuminated: "Spiritual", performance: "Performance", sheet: "Score",
    },
  },
};

export const arcPoints = movements.map((m, i) => ({
  x: 60 + (i / (movements.length - 1)) * 880,
  y: 20 + ((100 - m.arc) / 100) * 200,
  m,
}));
